################ Hungarian language ##################
[hu]
languageName = "Hu"
languageCode = "hu-hu"
contentDir = "content/hungarian"
weight = 1
################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2