############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About our sights"
url = "/about"
weight = 2

[[main]]
name = "Booking"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Visit Hungary Promo 2025"
url = "/promotions"

# footer menu
[[footer]]
name = "About our sights"
url = "/about"
weight = 1

[[footer]]
name = "Booking"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
