############# Hungarian navigation ##############

# main menu
[[main]]
name = "Főoldal"
url = "/"
weight = 1


[[main]]
name = "Vendégházaink"
url = "/authors"
weight = 2

[[main]]
name = "Foglalás"
url = "/hu/elements/"
weight = 3

[[main]]
name = "Ajánlatok"
url = "/promotions"
weight = 4

[[main]]
weight = 5
name = "További oldalak"

[[main]]
parent = "További oldalak"
name = "Látnivalók"
url = "/about"
weight = 6

[[main]]
parent = "További oldalak"
name = "Blog"
url = "/blog"
weight = 7

# [[main]]
# parent = "További oldalak"
# name = "Kapcsolat"
# url = "/contact"
# weight = 8

[[main]]
parent = "További oldalak"
name = "Kategóriák"
url = "/categories"
weight = 9

# footer menu
[[footer]]
name = "Látnivalók"
url = "/about"
weight = 1

[[footer]]
name = "Foglalás"
url = "/elements"
weight = 2

[[footer]]
name = "Adatvédelem"
url = "/privacy-policy"
weight = 3
