############# Hungarian navigation ##############

# main menu
[[main]]
name = "Főoldal"
url = "/"
weight = 1

[[main]]
name = "Látnivalók"
url = "/about"
weight = 2

[[main]]
name = "Elements"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Oldalak"

[[main]]
parent = "Oldalak"
name = "Blog"
url = "/blog"

[[main]]
parent = "Oldalak"
name = "Kapcsolat"
url = "/contact"

[[main]]
parent = "Oldalak"
name = "Authors"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Oldalak"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
