############# Hungarian navigation ##############

# main menu
[[main]]
name = "Főoldal"
url = "/"
weight = 1

[[main]]
name = "Látnivalók"
url = "/about"
weight = 2

[[main]]
name = "Foglalás"
url = "/hu/elements/"
weight = 3

[[main]]
weight = 4
name = "Visit Hungary Nyári Ajánlat 2025"
url = "/promotions"

# footer menu
[[footer]]
name = "Látnivalók"
url = "/about"
weight = 1

[[footer]]
name = "Foglalás"
url = "/elements"
weight = 2

[[footer]]
name = "Adatvédelem"
url = "/privacy-policy"
weight = 3
