############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Guest houses"
url = "/guesthouses"
weight = 2

# [[main]]
# name = "Booking"
# url = "/elements"
# weight = 3

[[main]]
name = "Promotions"
url = "/promotions"
weight = 4

[[main]]
name = "Pages"
weight = 5

[[main]]
parent = "Pages"
name = "Sights"
url = "/about"
weight = 6

[[main]]
parent = "Pages"
name = "Blog"
url = "/blog"
weight = 7

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"
weight = 8

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"
weight = 9




# footer menu
[[footer]]
name = "About our sights"
url = "/about"
weight = 1

[[footer]]
name = "Booking"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
